// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Consent struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	DocumentKey     string             `json:"document_key"`
	DocumentVersion string             `json:"document_version"`
	Source          string             `json:"source"`
	AcceptedAt      pgtype.Timestamptz `json:"accepted_at"`
	WithdrawnAt     pgtype.Timestamptz `json:"withdrawn_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type IdentityRef struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Provider  string             `json:"provider"`
	Subject   string             `json:"subject"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserProfile struct {
	UserID      uuid.UUID          `json:"user_id"`
	DisplayName string             `json:"display_name"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
