// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConsent = `-- name: CreateConsent :exec
INSERT INTO consents (id, user_id, document_key, document_version, source, accepted_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (user_id, document_key, document_version) DO NOTHING
`

type CreateConsentParams struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	DocumentKey     string             `json:"document_key"`
	DocumentVersion string             `json:"document_version"`
	Source          string             `json:"source"`
	AcceptedAt      pgtype.Timestamptz `json:"accepted_at"`
}

func (q *Queries) CreateConsent(ctx context.Context, arg CreateConsentParams) error {
	_, err := q.db.Exec(ctx, createConsent,
		arg.ID,
		arg.UserID,
		arg.DocumentKey,
		arg.DocumentVersion,
		arg.Source,
		arg.AcceptedAt,
	)
	return err
}

const createIdentityRef = `-- name: CreateIdentityRef :exec
INSERT INTO identity_refs (id, user_id, provider, subject)
VALUES ($1, $2, $3, $4)
`

type CreateIdentityRefParams struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
	Subject  string    `json:"subject"`
}

func (q *Queries) CreateIdentityRef(ctx context.Context, arg CreateIdentityRefParams) error {
	_, err := q.db.Exec(ctx, createIdentityRef,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.Subject,
	)
	return err
}

const createProfile = `-- name: CreateProfile :exec
INSERT INTO user_profiles (user_id, display_name)
VALUES ($1, $2)
ON CONFLICT (user_id) DO NOTHING
`

type CreateProfileParams struct {
	UserID      uuid.UUID `json:"user_id"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) error {
	_, err := q.db.Exec(ctx, createProfile, arg.UserID, arg.DisplayName)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id) VALUES ($1)
`

func (q *Queries) CreateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, createUser, id)
	return err
}

const getProfileByIdentity = `-- name: GetProfileByIdentity :one
SELECT u.id AS user_id,
       p.display_name,
       p.version,
       p.created_at,
       p.updated_at
FROM identity_refs i
JOIN users u ON u.id = i.user_id
JOIN user_profiles p ON p.user_id = u.id
WHERE i.provider = $1
  AND i.subject = $2
  AND u.status = 'active'
`

type GetProfileByIdentityParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

type GetProfileByIdentityRow struct {
	UserID      uuid.UUID          `json:"user_id"`
	DisplayName string             `json:"display_name"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetProfileByIdentity(ctx context.Context, arg GetProfileByIdentityParams) (GetProfileByIdentityRow, error) {
	row := q.db.QueryRow(ctx, getProfileByIdentity, arg.Provider, arg.Subject)
	var i GetProfileByIdentityRow
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserIDByIdentity = `-- name: GetUserIDByIdentity :one
SELECT user_id
FROM identity_refs
WHERE provider = $1 AND subject = $2
`

type GetUserIDByIdentityParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

func (q *Queries) GetUserIDByIdentity(ctx context.Context, arg GetUserIDByIdentityParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByIdentity, arg.Provider, arg.Subject)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const listConsentsByUser = `-- name: ListConsentsByUser :many
SELECT id, document_key, document_version, source, accepted_at, withdrawn_at
FROM consents
WHERE user_id = $1
ORDER BY accepted_at DESC, id DESC
`

type ListConsentsByUserRow struct {
	ID              uuid.UUID          `json:"id"`
	DocumentKey     string             `json:"document_key"`
	DocumentVersion string             `json:"document_version"`
	Source          string             `json:"source"`
	AcceptedAt      pgtype.Timestamptz `json:"accepted_at"`
	WithdrawnAt     pgtype.Timestamptz `json:"withdrawn_at"`
}

func (q *Queries) ListConsentsByUser(ctx context.Context, userID uuid.UUID) ([]ListConsentsByUserRow, error) {
	rows, err := q.db.Query(ctx, listConsentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConsentsByUserRow{}
	for rows.Next() {
		var i ListConsentsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentKey,
			&i.DocumentVersion,
			&i.Source,
			&i.AcceptedAt,
			&i.WithdrawnAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfileByIdentity = `-- name: UpdateProfileByIdentity :one
UPDATE user_profiles AS p
SET display_name = $1,
    version = p.version + 1,
    updated_at = now()
FROM identity_refs AS i, users AS u
WHERE i.provider = $2
  AND i.subject = $3
  AND i.user_id = u.id
  AND u.status = 'active'
  AND p.user_id = u.id
  AND p.version = $4
RETURNING p.user_id, p.display_name, p.version, p.created_at, p.updated_at
`

type UpdateProfileByIdentityParams struct {
	DisplayName     string `json:"display_name"`
	Provider        string `json:"provider"`
	Subject         string `json:"subject"`
	ExpectedVersion int64  `json:"expected_version"`
}

func (q *Queries) UpdateProfileByIdentity(ctx context.Context, arg UpdateProfileByIdentityParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, updateProfileByIdentity,
		arg.DisplayName,
		arg.Provider,
		arg.Subject,
		arg.ExpectedVersion,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
