// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConsent = `-- name: CreateConsent :exec
INSERT INTO consents (id, user_id, document_key, document_version, source, accepted_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, document_key, document_version) DO NOTHING
`

type CreateConsentParams struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	DocumentKey     string             `json:"document_key"`
	DocumentVersion string             `json:"document_version"`
	Source          string             `json:"source"`
	AcceptedAt      pgtype.Timestamptz `json:"accepted_at"`
}

func (q *Queries) CreateConsent(ctx context.Context, arg CreateConsentParams) error {
	_, err := q.db.Exec(ctx, createConsent,
		arg.ID,
		arg.UserID,
		arg.DocumentKey,
		arg.DocumentVersion,
		arg.Source,
		arg.AcceptedAt,
	)
	return err
}

const createDefaultProfile = `-- name: CreateDefaultProfile :exec
INSERT INTO user_profiles (user_id, display_name)
VALUES ($1, 'Athlete')
ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) CreateDefaultProfile(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createDefaultProfile, userID)
	return err
}

const createIdempotencyRecord = `-- name: CreateIdempotencyRecord :exec
INSERT INTO onboarding_idempotency (user_id, idempotency_key, request_hash, response_snapshot)
VALUES ($1, $2, $3, $4)
`

type CreateIdempotencyRecordParams struct {
	UserID           uuid.UUID `json:"user_id"`
	IdempotencyKey   string    `json:"idempotency_key"`
	RequestHash      []byte    `json:"request_hash"`
	ResponseSnapshot []byte    `json:"response_snapshot"`
}

func (q *Queries) CreateIdempotencyRecord(ctx context.Context, arg CreateIdempotencyRecordParams) error {
	_, err := q.db.Exec(ctx, createIdempotencyRecord,
		arg.UserID,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ResponseSnapshot,
	)
	return err
}

const createIdentity = `-- name: CreateIdentity :exec
INSERT INTO identity_refs (id, user_id, provider, subject)
VALUES ($1, $2, $3, $4)
`

type CreateIdentityParams struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
	Subject  string    `json:"subject"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) error {
	_, err := q.db.Exec(ctx, createIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.Subject,
	)
	return err
}

const createOnboarding = `-- name: CreateOnboarding :exec
INSERT INTO user_onboarding (user_id) VALUES ($1)
ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) CreateOnboarding(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createOnboarding, userID)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id) VALUES ($1)
`

func (q *Queries) CreateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, createUser, id)
	return err
}

const getIdempotencyRecord = `-- name: GetIdempotencyRecord :one
SELECT request_hash, response_snapshot
FROM onboarding_idempotency
WHERE user_id = $1 AND idempotency_key = $2
`

type GetIdempotencyRecordParams struct {
	UserID         uuid.UUID `json:"user_id"`
	IdempotencyKey string    `json:"idempotency_key"`
}

type GetIdempotencyRecordRow struct {
	RequestHash      []byte `json:"request_hash"`
	ResponseSnapshot []byte `json:"response_snapshot"`
}

func (q *Queries) GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (GetIdempotencyRecordRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyRecord, arg.UserID, arg.IdempotencyKey)
	var i GetIdempotencyRecordRow
	err := row.Scan(&i.RequestHash, &i.ResponseSnapshot)
	return i, err
}

const getIdentityUser = `-- name: GetIdentityUser :one
SELECT i.user_id, u.status
FROM identity_refs i
JOIN users u ON u.id = i.user_id
WHERE i.provider = $1
  AND i.subject = $2
`

type GetIdentityUserParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

type GetIdentityUserRow struct {
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
}

func (q *Queries) GetIdentityUser(ctx context.Context, arg GetIdentityUserParams) (GetIdentityUserRow, error) {
	row := q.db.QueryRow(ctx, getIdentityUser, arg.Provider, arg.Subject)
	var i GetIdentityUserRow
	err := row.Scan(&i.UserID, &i.Status)
	return i, err
}

const getOnboardingByIdentity = `-- name: GetOnboardingByIdentity :one
SELECT o.user_id, o.adult_attested_at, o.terms_version, o.terms_accepted_at, o.privacy_version, o.privacy_accepted_at, o.timezone, o.units, o.primary_goal, o.experience_level, o.weekly_availability, o.session_duration_minutes, o.equipment_access, o.diet_preference, o.safety_acknowledged_at, o.current_step, o.state, o.version, o.completed_at, o.created_at, o.updated_at
FROM identity_refs i
JOIN users u ON u.id = i.user_id
JOIN user_onboarding o ON o.user_id = u.id
WHERE i.provider = $1
  AND i.subject = $2
  AND u.status = 'active'
`

type GetOnboardingByIdentityParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

func (q *Queries) GetOnboardingByIdentity(ctx context.Context, arg GetOnboardingByIdentityParams) (UserOnboarding, error) {
	row := q.db.QueryRow(ctx, getOnboardingByIdentity, arg.Provider, arg.Subject)
	var i UserOnboarding
	err := row.Scan(
		&i.UserID,
		&i.AdultAttestedAt,
		&i.TermsVersion,
		&i.TermsAcceptedAt,
		&i.PrivacyVersion,
		&i.PrivacyAcceptedAt,
		&i.Timezone,
		&i.Units,
		&i.PrimaryGoal,
		&i.ExperienceLevel,
		&i.WeeklyAvailability,
		&i.SessionDurationMinutes,
		&i.EquipmentAccess,
		&i.DietPreference,
		&i.SafetyAcknowledgedAt,
		&i.CurrentStep,
		&i.State,
		&i.Version,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockOnboarding = `-- name: LockOnboarding :one
SELECT user_id, adult_attested_at, terms_version, terms_accepted_at, privacy_version, privacy_accepted_at, timezone, units, primary_goal, experience_level, weekly_availability, session_duration_minutes, equipment_access, diet_preference, safety_acknowledged_at, current_step, state, version, completed_at, created_at, updated_at FROM user_onboarding
WHERE user_id = $1
FOR UPDATE
`

func (q *Queries) LockOnboarding(ctx context.Context, userID uuid.UUID) (UserOnboarding, error) {
	row := q.db.QueryRow(ctx, lockOnboarding, userID)
	var i UserOnboarding
	err := row.Scan(
		&i.UserID,
		&i.AdultAttestedAt,
		&i.TermsVersion,
		&i.TermsAcceptedAt,
		&i.PrivacyVersion,
		&i.PrivacyAcceptedAt,
		&i.Timezone,
		&i.Units,
		&i.PrimaryGoal,
		&i.ExperienceLevel,
		&i.WeeklyAvailability,
		&i.SessionDurationMinutes,
		&i.EquipmentAccess,
		&i.DietPreference,
		&i.SafetyAcknowledgedAt,
		&i.CurrentStep,
		&i.State,
		&i.Version,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockOnboardingIdentity = `-- name: LockOnboardingIdentity :exec
SELECT pg_advisory_xact_lock(hashtextextended($1 || E'\x1f' || $2, 0))
`

type LockOnboardingIdentityParams struct {
	Provider *string `json:"provider"`
	Subject  *string `json:"subject"`
}

func (q *Queries) LockOnboardingIdentity(ctx context.Context, arg LockOnboardingIdentityParams) error {
	_, err := q.db.Exec(ctx, lockOnboardingIdentity, arg.Provider, arg.Subject)
	return err
}

const updateOnboarding = `-- name: UpdateOnboarding :one
UPDATE user_onboarding
SET adult_attested_at = $1,
    terms_version = $2,
    terms_accepted_at = $3,
    privacy_version = $4,
    privacy_accepted_at = $5,
    timezone = $6,
    units = $7,
    primary_goal = $8,
    experience_level = $9,
    weekly_availability = $10,
    session_duration_minutes = $11,
    equipment_access = $12,
    diet_preference = $13,
    safety_acknowledged_at = $14,
    current_step = $15,
    state = $16,
    completed_at = $17,
    version = version + 1,
    updated_at = $18
WHERE user_id = $19
RETURNING user_id, adult_attested_at, terms_version, terms_accepted_at, privacy_version, privacy_accepted_at, timezone, units, primary_goal, experience_level, weekly_availability, session_duration_minutes, equipment_access, diet_preference, safety_acknowledged_at, current_step, state, version, completed_at, created_at, updated_at
`

type UpdateOnboardingParams struct {
	AdultAttestedAt        pgtype.Timestamptz `json:"adult_attested_at"`
	TermsVersion           *string            `json:"terms_version"`
	TermsAcceptedAt        pgtype.Timestamptz `json:"terms_accepted_at"`
	PrivacyVersion         *string            `json:"privacy_version"`
	PrivacyAcceptedAt      pgtype.Timestamptz `json:"privacy_accepted_at"`
	Timezone               *string            `json:"timezone"`
	Units                  *string            `json:"units"`
	PrimaryGoal            *string            `json:"primary_goal"`
	ExperienceLevel        *string            `json:"experience_level"`
	WeeklyAvailability     *int16             `json:"weekly_availability"`
	SessionDurationMinutes *int16             `json:"session_duration_minutes"`
	EquipmentAccess        []string           `json:"equipment_access"`
	DietPreference         *string            `json:"diet_preference"`
	SafetyAcknowledgedAt   pgtype.Timestamptz `json:"safety_acknowledged_at"`
	CurrentStep            int16              `json:"current_step"`
	State                  string             `json:"state"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	UserID                 uuid.UUID          `json:"user_id"`
}

func (q *Queries) UpdateOnboarding(ctx context.Context, arg UpdateOnboardingParams) (UserOnboarding, error) {
	row := q.db.QueryRow(ctx, updateOnboarding,
		arg.AdultAttestedAt,
		arg.TermsVersion,
		arg.TermsAcceptedAt,
		arg.PrivacyVersion,
		arg.PrivacyAcceptedAt,
		arg.Timezone,
		arg.Units,
		arg.PrimaryGoal,
		arg.ExperienceLevel,
		arg.WeeklyAvailability,
		arg.SessionDurationMinutes,
		arg.EquipmentAccess,
		arg.DietPreference,
		arg.SafetyAcknowledgedAt,
		arg.CurrentStep,
		arg.State,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.UserID,
	)
	var i UserOnboarding
	err := row.Scan(
		&i.UserID,
		&i.AdultAttestedAt,
		&i.TermsVersion,
		&i.TermsAcceptedAt,
		&i.PrivacyVersion,
		&i.PrivacyAcceptedAt,
		&i.Timezone,
		&i.Units,
		&i.PrimaryGoal,
		&i.ExperienceLevel,
		&i.WeeklyAvailability,
		&i.SessionDurationMinutes,
		&i.EquipmentAccess,
		&i.DietPreference,
		&i.SafetyAcknowledgedAt,
		&i.CurrentStep,
		&i.State,
		&i.Version,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
